language: clojure
lein: lein2

before_install:
  - sudo apt-get install wget -qq
  - sudo apt-get install unzip -qq
  - echo "Fetching V8..."
  - git clone --branch=master --depth=1 --quiet git://github.com/v8/v8.git v8 && cd v8
  - echo "Building V8"
  - make dependencies
  - make native
  - cd ./out/native/
  - export V8_HOME=`pwd`
  - cd ../../../
  - pwd
